# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.26.2/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.26.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/quentin/Developement/CookingApp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/quentin/Developement/CookingApp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.25.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.26.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.26.2/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.26.2/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.26.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.26.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.26.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.26.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/quentin/Developement/CookingApp/CMakeFiles /Users/quentin/Developement/CookingApp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/quentin/Developement/CookingApp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CookingApp

# Build rule for target.
CookingApp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CookingApp
.PHONY : CookingApp

# fast build rule for target.
CookingApp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/build
.PHONY : CookingApp/fast

#=============================================================================
# Target rules for targets named CookingApp_autogen

# Build rule for target.
CookingApp_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CookingApp_autogen
.PHONY : CookingApp_autogen

# fast build rule for target.
CookingApp_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp_autogen.dir/build.make CMakeFiles/CookingApp_autogen.dir/build
.PHONY : CookingApp_autogen/fast

CookingApp_autogen/EWIEGA46WW/qrc_resources.o: CookingApp_autogen/EWIEGA46WW/qrc_resources.cpp.o
.PHONY : CookingApp_autogen/EWIEGA46WW/qrc_resources.o

# target to build an object file
CookingApp_autogen/EWIEGA46WW/qrc_resources.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/CookingApp_autogen/EWIEGA46WW/qrc_resources.cpp.o
.PHONY : CookingApp_autogen/EWIEGA46WW/qrc_resources.cpp.o

CookingApp_autogen/EWIEGA46WW/qrc_resources.i: CookingApp_autogen/EWIEGA46WW/qrc_resources.cpp.i
.PHONY : CookingApp_autogen/EWIEGA46WW/qrc_resources.i

# target to preprocess a source file
CookingApp_autogen/EWIEGA46WW/qrc_resources.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/CookingApp_autogen/EWIEGA46WW/qrc_resources.cpp.i
.PHONY : CookingApp_autogen/EWIEGA46WW/qrc_resources.cpp.i

CookingApp_autogen/EWIEGA46WW/qrc_resources.s: CookingApp_autogen/EWIEGA46WW/qrc_resources.cpp.s
.PHONY : CookingApp_autogen/EWIEGA46WW/qrc_resources.s

# target to generate assembly for a file
CookingApp_autogen/EWIEGA46WW/qrc_resources.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/CookingApp_autogen/EWIEGA46WW/qrc_resources.cpp.s
.PHONY : CookingApp_autogen/EWIEGA46WW/qrc_resources.cpp.s

CookingApp_autogen/mocs_compilation.o: CookingApp_autogen/mocs_compilation.cpp.o
.PHONY : CookingApp_autogen/mocs_compilation.o

# target to build an object file
CookingApp_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/CookingApp_autogen/mocs_compilation.cpp.o
.PHONY : CookingApp_autogen/mocs_compilation.cpp.o

CookingApp_autogen/mocs_compilation.i: CookingApp_autogen/mocs_compilation.cpp.i
.PHONY : CookingApp_autogen/mocs_compilation.i

# target to preprocess a source file
CookingApp_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/CookingApp_autogen/mocs_compilation.cpp.i
.PHONY : CookingApp_autogen/mocs_compilation.cpp.i

CookingApp_autogen/mocs_compilation.s: CookingApp_autogen/mocs_compilation.cpp.s
.PHONY : CookingApp_autogen/mocs_compilation.s

# target to generate assembly for a file
CookingApp_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/CookingApp_autogen/mocs_compilation.cpp.s
.PHONY : CookingApp_autogen/mocs_compilation.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/main.cpp.s
.PHONY : main.cpp.s

qt/MainWindow.o: qt/MainWindow.cpp.o
.PHONY : qt/MainWindow.o

# target to build an object file
qt/MainWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/qt/MainWindow.cpp.o
.PHONY : qt/MainWindow.cpp.o

qt/MainWindow.i: qt/MainWindow.cpp.i
.PHONY : qt/MainWindow.i

# target to preprocess a source file
qt/MainWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/qt/MainWindow.cpp.i
.PHONY : qt/MainWindow.cpp.i

qt/MainWindow.s: qt/MainWindow.cpp.s
.PHONY : qt/MainWindow.s

# target to generate assembly for a file
qt/MainWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/qt/MainWindow.cpp.s
.PHONY : qt/MainWindow.cpp.s

qt/dialogs/IngredientsDialog.o: qt/dialogs/IngredientsDialog.cpp.o
.PHONY : qt/dialogs/IngredientsDialog.o

# target to build an object file
qt/dialogs/IngredientsDialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/qt/dialogs/IngredientsDialog.cpp.o
.PHONY : qt/dialogs/IngredientsDialog.cpp.o

qt/dialogs/IngredientsDialog.i: qt/dialogs/IngredientsDialog.cpp.i
.PHONY : qt/dialogs/IngredientsDialog.i

# target to preprocess a source file
qt/dialogs/IngredientsDialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/qt/dialogs/IngredientsDialog.cpp.i
.PHONY : qt/dialogs/IngredientsDialog.cpp.i

qt/dialogs/IngredientsDialog.s: qt/dialogs/IngredientsDialog.cpp.s
.PHONY : qt/dialogs/IngredientsDialog.s

# target to generate assembly for a file
qt/dialogs/IngredientsDialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/qt/dialogs/IngredientsDialog.cpp.s
.PHONY : qt/dialogs/IngredientsDialog.cpp.s

qt/dialogs/SearchDialog.o: qt/dialogs/SearchDialog.cpp.o
.PHONY : qt/dialogs/SearchDialog.o

# target to build an object file
qt/dialogs/SearchDialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/qt/dialogs/SearchDialog.cpp.o
.PHONY : qt/dialogs/SearchDialog.cpp.o

qt/dialogs/SearchDialog.i: qt/dialogs/SearchDialog.cpp.i
.PHONY : qt/dialogs/SearchDialog.i

# target to preprocess a source file
qt/dialogs/SearchDialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/qt/dialogs/SearchDialog.cpp.i
.PHONY : qt/dialogs/SearchDialog.cpp.i

qt/dialogs/SearchDialog.s: qt/dialogs/SearchDialog.cpp.s
.PHONY : qt/dialogs/SearchDialog.s

# target to generate assembly for a file
qt/dialogs/SearchDialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/qt/dialogs/SearchDialog.cpp.s
.PHONY : qt/dialogs/SearchDialog.cpp.s

qt/recipe/RecipeCard.o: qt/recipe/RecipeCard.cpp.o
.PHONY : qt/recipe/RecipeCard.o

# target to build an object file
qt/recipe/RecipeCard.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/qt/recipe/RecipeCard.cpp.o
.PHONY : qt/recipe/RecipeCard.cpp.o

qt/recipe/RecipeCard.i: qt/recipe/RecipeCard.cpp.i
.PHONY : qt/recipe/RecipeCard.i

# target to preprocess a source file
qt/recipe/RecipeCard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/qt/recipe/RecipeCard.cpp.i
.PHONY : qt/recipe/RecipeCard.cpp.i

qt/recipe/RecipeCard.s: qt/recipe/RecipeCard.cpp.s
.PHONY : qt/recipe/RecipeCard.s

# target to generate assembly for a file
qt/recipe/RecipeCard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/qt/recipe/RecipeCard.cpp.s
.PHONY : qt/recipe/RecipeCard.cpp.s

qt/recipe/RecipeDetails.o: qt/recipe/RecipeDetails.cpp.o
.PHONY : qt/recipe/RecipeDetails.o

# target to build an object file
qt/recipe/RecipeDetails.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/qt/recipe/RecipeDetails.cpp.o
.PHONY : qt/recipe/RecipeDetails.cpp.o

qt/recipe/RecipeDetails.i: qt/recipe/RecipeDetails.cpp.i
.PHONY : qt/recipe/RecipeDetails.i

# target to preprocess a source file
qt/recipe/RecipeDetails.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/qt/recipe/RecipeDetails.cpp.i
.PHONY : qt/recipe/RecipeDetails.cpp.i

qt/recipe/RecipeDetails.s: qt/recipe/RecipeDetails.cpp.s
.PHONY : qt/recipe/RecipeDetails.s

# target to generate assembly for a file
qt/recipe/RecipeDetails.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/qt/recipe/RecipeDetails.cpp.s
.PHONY : qt/recipe/RecipeDetails.cpp.s

qt/recipe/RecipeGrid.o: qt/recipe/RecipeGrid.cpp.o
.PHONY : qt/recipe/RecipeGrid.o

# target to build an object file
qt/recipe/RecipeGrid.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/qt/recipe/RecipeGrid.cpp.o
.PHONY : qt/recipe/RecipeGrid.cpp.o

qt/recipe/RecipeGrid.i: qt/recipe/RecipeGrid.cpp.i
.PHONY : qt/recipe/RecipeGrid.i

# target to preprocess a source file
qt/recipe/RecipeGrid.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/qt/recipe/RecipeGrid.cpp.i
.PHONY : qt/recipe/RecipeGrid.cpp.i

qt/recipe/RecipeGrid.s: qt/recipe/RecipeGrid.cpp.s
.PHONY : qt/recipe/RecipeGrid.s

# target to generate assembly for a file
qt/recipe/RecipeGrid.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/qt/recipe/RecipeGrid.cpp.s
.PHONY : qt/recipe/RecipeGrid.cpp.s

qt/tools/FileDownloader.o: qt/tools/FileDownloader.cpp.o
.PHONY : qt/tools/FileDownloader.o

# target to build an object file
qt/tools/FileDownloader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/qt/tools/FileDownloader.cpp.o
.PHONY : qt/tools/FileDownloader.cpp.o

qt/tools/FileDownloader.i: qt/tools/FileDownloader.cpp.i
.PHONY : qt/tools/FileDownloader.i

# target to preprocess a source file
qt/tools/FileDownloader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/qt/tools/FileDownloader.cpp.i
.PHONY : qt/tools/FileDownloader.cpp.i

qt/tools/FileDownloader.s: qt/tools/FileDownloader.cpp.s
.PHONY : qt/tools/FileDownloader.s

# target to generate assembly for a file
qt/tools/FileDownloader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/qt/tools/FileDownloader.cpp.s
.PHONY : qt/tools/FileDownloader.cpp.s

qt/tools/Tools.o: qt/tools/Tools.cpp.o
.PHONY : qt/tools/Tools.o

# target to build an object file
qt/tools/Tools.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/qt/tools/Tools.cpp.o
.PHONY : qt/tools/Tools.cpp.o

qt/tools/Tools.i: qt/tools/Tools.cpp.i
.PHONY : qt/tools/Tools.i

# target to preprocess a source file
qt/tools/Tools.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/qt/tools/Tools.cpp.i
.PHONY : qt/tools/Tools.cpp.i

qt/tools/Tools.s: qt/tools/Tools.cpp.s
.PHONY : qt/tools/Tools.s

# target to generate assembly for a file
qt/tools/Tools.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/qt/tools/Tools.cpp.s
.PHONY : qt/tools/Tools.cpp.s

qt/widgets/QClickableImage.o: qt/widgets/QClickableImage.cpp.o
.PHONY : qt/widgets/QClickableImage.o

# target to build an object file
qt/widgets/QClickableImage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/qt/widgets/QClickableImage.cpp.o
.PHONY : qt/widgets/QClickableImage.cpp.o

qt/widgets/QClickableImage.i: qt/widgets/QClickableImage.cpp.i
.PHONY : qt/widgets/QClickableImage.i

# target to preprocess a source file
qt/widgets/QClickableImage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/qt/widgets/QClickableImage.cpp.i
.PHONY : qt/widgets/QClickableImage.cpp.i

qt/widgets/QClickableImage.s: qt/widgets/QClickableImage.cpp.s
.PHONY : qt/widgets/QClickableImage.s

# target to generate assembly for a file
qt/widgets/QClickableImage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/qt/widgets/QClickableImage.cpp.s
.PHONY : qt/widgets/QClickableImage.cpp.s

qt/widgets/QIconLabel.o: qt/widgets/QIconLabel.cpp.o
.PHONY : qt/widgets/QIconLabel.o

# target to build an object file
qt/widgets/QIconLabel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/qt/widgets/QIconLabel.cpp.o
.PHONY : qt/widgets/QIconLabel.cpp.o

qt/widgets/QIconLabel.i: qt/widgets/QIconLabel.cpp.i
.PHONY : qt/widgets/QIconLabel.i

# target to preprocess a source file
qt/widgets/QIconLabel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/qt/widgets/QIconLabel.cpp.i
.PHONY : qt/widgets/QIconLabel.cpp.i

qt/widgets/QIconLabel.s: qt/widgets/QIconLabel.cpp.s
.PHONY : qt/widgets/QIconLabel.s

# target to generate assembly for a file
qt/widgets/QIconLabel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/qt/widgets/QIconLabel.cpp.s
.PHONY : qt/widgets/QIconLabel.cpp.s

recipe/Recipe.o: recipe/Recipe.cpp.o
.PHONY : recipe/Recipe.o

# target to build an object file
recipe/Recipe.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/recipe/Recipe.cpp.o
.PHONY : recipe/Recipe.cpp.o

recipe/Recipe.i: recipe/Recipe.cpp.i
.PHONY : recipe/Recipe.i

# target to preprocess a source file
recipe/Recipe.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/recipe/Recipe.cpp.i
.PHONY : recipe/Recipe.cpp.i

recipe/Recipe.s: recipe/Recipe.cpp.s
.PHONY : recipe/Recipe.s

# target to generate assembly for a file
recipe/Recipe.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/recipe/Recipe.cpp.s
.PHONY : recipe/Recipe.cpp.s

recipe/RecipeFavourite.o: recipe/RecipeFavourite.cpp.o
.PHONY : recipe/RecipeFavourite.o

# target to build an object file
recipe/RecipeFavourite.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/recipe/RecipeFavourite.cpp.o
.PHONY : recipe/RecipeFavourite.cpp.o

recipe/RecipeFavourite.i: recipe/RecipeFavourite.cpp.i
.PHONY : recipe/RecipeFavourite.i

# target to preprocess a source file
recipe/RecipeFavourite.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/recipe/RecipeFavourite.cpp.i
.PHONY : recipe/RecipeFavourite.cpp.i

recipe/RecipeFavourite.s: recipe/RecipeFavourite.cpp.s
.PHONY : recipe/RecipeFavourite.s

# target to generate assembly for a file
recipe/RecipeFavourite.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/recipe/RecipeFavourite.cpp.s
.PHONY : recipe/RecipeFavourite.cpp.s

recipe/elements/Ingredient.o: recipe/elements/Ingredient.cpp.o
.PHONY : recipe/elements/Ingredient.o

# target to build an object file
recipe/elements/Ingredient.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/recipe/elements/Ingredient.cpp.o
.PHONY : recipe/elements/Ingredient.cpp.o

recipe/elements/Ingredient.i: recipe/elements/Ingredient.cpp.i
.PHONY : recipe/elements/Ingredient.i

# target to preprocess a source file
recipe/elements/Ingredient.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/recipe/elements/Ingredient.cpp.i
.PHONY : recipe/elements/Ingredient.cpp.i

recipe/elements/Ingredient.s: recipe/elements/Ingredient.cpp.s
.PHONY : recipe/elements/Ingredient.s

# target to generate assembly for a file
recipe/elements/Ingredient.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/recipe/elements/Ingredient.cpp.s
.PHONY : recipe/elements/Ingredient.cpp.s

recipe/elements/Instruction.o: recipe/elements/Instruction.cpp.o
.PHONY : recipe/elements/Instruction.o

# target to build an object file
recipe/elements/Instruction.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/recipe/elements/Instruction.cpp.o
.PHONY : recipe/elements/Instruction.cpp.o

recipe/elements/Instruction.i: recipe/elements/Instruction.cpp.i
.PHONY : recipe/elements/Instruction.i

# target to preprocess a source file
recipe/elements/Instruction.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/recipe/elements/Instruction.cpp.i
.PHONY : recipe/elements/Instruction.cpp.i

recipe/elements/Instruction.s: recipe/elements/Instruction.cpp.s
.PHONY : recipe/elements/Instruction.s

# target to generate assembly for a file
recipe/elements/Instruction.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/recipe/elements/Instruction.cpp.s
.PHONY : recipe/elements/Instruction.cpp.s

recipe/elements/Measure.o: recipe/elements/Measure.cpp.o
.PHONY : recipe/elements/Measure.o

# target to build an object file
recipe/elements/Measure.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/recipe/elements/Measure.cpp.o
.PHONY : recipe/elements/Measure.cpp.o

recipe/elements/Measure.i: recipe/elements/Measure.cpp.i
.PHONY : recipe/elements/Measure.i

# target to preprocess a source file
recipe/elements/Measure.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/recipe/elements/Measure.cpp.i
.PHONY : recipe/elements/Measure.cpp.i

recipe/elements/Measure.s: recipe/elements/Measure.cpp.s
.PHONY : recipe/elements/Measure.s

# target to generate assembly for a file
recipe/elements/Measure.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/recipe/elements/Measure.cpp.s
.PHONY : recipe/elements/Measure.cpp.s

recipe/scrapper/Scrapper.o: recipe/scrapper/Scrapper.cpp.o
.PHONY : recipe/scrapper/Scrapper.o

# target to build an object file
recipe/scrapper/Scrapper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/recipe/scrapper/Scrapper.cpp.o
.PHONY : recipe/scrapper/Scrapper.cpp.o

recipe/scrapper/Scrapper.i: recipe/scrapper/Scrapper.cpp.i
.PHONY : recipe/scrapper/Scrapper.i

# target to preprocess a source file
recipe/scrapper/Scrapper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/recipe/scrapper/Scrapper.cpp.i
.PHONY : recipe/scrapper/Scrapper.cpp.i

recipe/scrapper/Scrapper.s: recipe/scrapper/Scrapper.cpp.s
.PHONY : recipe/scrapper/Scrapper.s

# target to generate assembly for a file
recipe/scrapper/Scrapper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CookingApp.dir/build.make CMakeFiles/CookingApp.dir/recipe/scrapper/Scrapper.cpp.s
.PHONY : recipe/scrapper/Scrapper.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... CookingApp_autogen"
	@echo "... CookingApp"
	@echo "... CookingApp_autogen/EWIEGA46WW/qrc_resources.o"
	@echo "... CookingApp_autogen/EWIEGA46WW/qrc_resources.i"
	@echo "... CookingApp_autogen/EWIEGA46WW/qrc_resources.s"
	@echo "... CookingApp_autogen/mocs_compilation.o"
	@echo "... CookingApp_autogen/mocs_compilation.i"
	@echo "... CookingApp_autogen/mocs_compilation.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... qt/MainWindow.o"
	@echo "... qt/MainWindow.i"
	@echo "... qt/MainWindow.s"
	@echo "... qt/dialogs/IngredientsDialog.o"
	@echo "... qt/dialogs/IngredientsDialog.i"
	@echo "... qt/dialogs/IngredientsDialog.s"
	@echo "... qt/dialogs/SearchDialog.o"
	@echo "... qt/dialogs/SearchDialog.i"
	@echo "... qt/dialogs/SearchDialog.s"
	@echo "... qt/recipe/RecipeCard.o"
	@echo "... qt/recipe/RecipeCard.i"
	@echo "... qt/recipe/RecipeCard.s"
	@echo "... qt/recipe/RecipeDetails.o"
	@echo "... qt/recipe/RecipeDetails.i"
	@echo "... qt/recipe/RecipeDetails.s"
	@echo "... qt/recipe/RecipeGrid.o"
	@echo "... qt/recipe/RecipeGrid.i"
	@echo "... qt/recipe/RecipeGrid.s"
	@echo "... qt/tools/FileDownloader.o"
	@echo "... qt/tools/FileDownloader.i"
	@echo "... qt/tools/FileDownloader.s"
	@echo "... qt/tools/Tools.o"
	@echo "... qt/tools/Tools.i"
	@echo "... qt/tools/Tools.s"
	@echo "... qt/widgets/QClickableImage.o"
	@echo "... qt/widgets/QClickableImage.i"
	@echo "... qt/widgets/QClickableImage.s"
	@echo "... qt/widgets/QIconLabel.o"
	@echo "... qt/widgets/QIconLabel.i"
	@echo "... qt/widgets/QIconLabel.s"
	@echo "... recipe/Recipe.o"
	@echo "... recipe/Recipe.i"
	@echo "... recipe/Recipe.s"
	@echo "... recipe/RecipeFavourite.o"
	@echo "... recipe/RecipeFavourite.i"
	@echo "... recipe/RecipeFavourite.s"
	@echo "... recipe/elements/Ingredient.o"
	@echo "... recipe/elements/Ingredient.i"
	@echo "... recipe/elements/Ingredient.s"
	@echo "... recipe/elements/Instruction.o"
	@echo "... recipe/elements/Instruction.i"
	@echo "... recipe/elements/Instruction.s"
	@echo "... recipe/elements/Measure.o"
	@echo "... recipe/elements/Measure.i"
	@echo "... recipe/elements/Measure.s"
	@echo "... recipe/scrapper/Scrapper.o"
	@echo "... recipe/scrapper/Scrapper.i"
	@echo "... recipe/scrapper/Scrapper.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

